# Reusable workflow to trigger fixture regeneration in tester repos.
# The tester repo should have a defined repo secret with repo, workflow access # named `TESTER_FIXTURE_GENERATION_GITHUB_TOKEN`.
# The repo also needs to define `make test` as a job in the Makefile.
# The workflow will trigger on a `regenerate-fixtures` label on a PR.
# While calling this workflow, the caller can pass all its secrets using:
# secrets: inherit
name: Trigger Fixture Regeneration

on:
  workflow_call:
    inputs:
      tester_repo:
        description: "The repo to regenerate fixtures for"
        required: true
        type: string

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Regenerate Fixtures
        uses: ./.github/actions/fixtures@CC-1779-2
        with:
          tester_repo: ${{ inputs.tester_repo }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fixture_generation_token: ${{ secrets.TESTER_FIXTURE_GENERATION_GITHUB_TOKEN }}
