name: Trigger Fixture Regeneration

on:
  workflow_call:  
    inputs:
      label:
        description: "Label that triggers fixture regeneration"
        required: true
        type: string

jobs:
  trigger_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the required label was applied
        id: check_label
        run: |
          if [[ "${{ github.event.pull_request.labels.*.name }}" ==  "${{ inputs.label }}" ]]; then
            echo "::set-output name=label_matched::true"
          else
            echo "::set-output name=label_matched::false"
            echo "::set-output name=skip_job::true"
          fi

      - name: Skip job if label does not match
        if: steps.check_label.outputs.skip_job == 'true'
        run: echo "Skipping job because label does not match" && exit 1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RYAN_FIXTURE_GEN_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x

      - uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Triggered a [Github Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) job to update fixtures.

      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: regenerate-fixtures

      - name: Regenerate Fixtures
        run: CODECRAFTERS_RECORD_FIXTURES=true make test 

      - name: Update Fixtures
        run: |
          git config --global user.email "ryan-gg@outlook.com"
          git config --global user.name "Ryan Gang"
          git remote set-url origin https://ryan-gang:${{ secrets.RYAN_FIXTURE_GEN_PAT }}@github.com/codecrafters-io/shell-tester.git
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git diff --quiet || (git add . && git commit -m "ci: add regenerated fixtures" && git push)
